### ISSUE TITLE
Proper reading procedure

### ISSUE THREAD

**Issue by alekspickle** [amqp-rs/lapin#373]
I understand that this is more of a AMQP specific, but is there some predefined method how to read the queue with timeout on when to stop reading?

### Context
I run two `tokio::spawn` tasks:
1. Publisher that posts messages with 250mcsecs interval
2. Reader that reads thow messages.

The whole thing is rather POC, but I need it to be the one process, and in this case do not really see the difference if it were separate crate.

So what I am struggling with is the fact that with `while let Some(delivery) = sub.next().await {` expression I don't see the way how I can stop reading ONLY IF the last message was read for example 2 secs ago.

Maybe it is my lack of knowledge in async but if some1 would point me in the right direction I'd appreciate it!

**Comment by tdejager** [comment]
Wouldn't you be able to make your own cancellation with `tokio::select!` for example? https://docs.rs/tokio/latest/tokio/macro.select.html#

**Comment by Keruspe** [comment]
You could indeed use some timeout future machinery, and call basic_cancel if you hit the timeout.

**Comment by alekspickle** [comment]
That's what I ended up doing :man_shrugging: 
```

           let sleep = tokio::time::sleep(Duration::from_secs(2));
            tokio::pin!(sleep);
            let delivery = tokio::select! {
                success = sub.try_next() => Ok(success?),
                _ = &mut sleep => Err(anyhow::anyhow!("No messages"))
            };

```

I'm sure it can be done better.
It would be cool to have such functionality built-in though.
I guess a wrapper providing this escape hatch is fine but not pretty.

**Comment by Keruspe** [comment]
Consumers offer you better ack management but cancel is racy by design, like while you're cancelling the server still sends messages in background. Basic_get is oneshot this way you can handle termination more freely and as a bonus you get how many messages were in the queue when delivering you the message in the metadata. Only caveat is that's it's really a polling approach and not a push/notif one. This has advantages and drawbacks but might very well fit your use case. Like you can basic get + sleep 0.25 and store a timestamp when receiving a message, and when not receiving one you compare with the time stamp stored and decide if you want to continue or not
