### ISSUE TITLE
invalid channel: 0 error

### ISSUE THREAD

**Issue by luca-iachini** [amqp-rs/lapin#382]
Hello,
first of all, thanks for the great library. 
sometimes, I receive `Invalid channel: 0` when I publish a message on a queue, do you know why that happens?
The following is the piece of code that raises the error:
```rust
fn send_message(msg: &[u8]) -> Result<()> {
        let conn = Connection::connect(&addr, ConnectionProperties::default()).await?;
        let channel = conn.create_channel().await?;
        channel
            .basic_publish(
                "",
                "messages",
                BasicPublishOptions::default(),
                msg,
                BasicProperties::default(),
            )
            .await?;
       Ok(())
}
```
That function opens a new connection, creates a channel, and sends a message on every invocation.
When I see that error, the client sent the message successfully, so it does not impact the normal flow of the application.
I guess that the client receives messages from the server after it dropped channel 0. 

Any help would be very appreciated.

**Comment by luca-iachini** [comment]
That example is taken from a test. it occurs more frequently in cases where the connection is dropped immediately after usage.

**Comment by luca-iachini** [comment]
sorry, I don't have a test account to share. Good to know that you have time to debug it :smiley:

**Comment by oliverbrowneprima** [comment]
Hey @Keruspe, after a little digging (I work with @luca-iachini, for reference), I have a question about the logic of `Channels::set_connection_closed` - it `drain`s the `channels` map, sending an internal rpc `RemoveChannel` command for each found channel, which results in a call to `Channels::remove`, which tries to remove the channel from the `channels` internal map... which has just been `drain`ed? 

Isn't that a double-remove? I know I must be missing something, since this error isn't perfectly reproducible?

**Comment by Keruspe** [comment]
It doesn’t send a RemoveChannel IPC there btw

**Comment by oliverbrowneprima** [comment]
`Channel::set_closed` calls `InternalRPCHandle::remove_channel` no?

**Comment by Keruspe** [comment]
You are absolutely right.
Just did some more tests and we can simplify all of this!

**Comment by oliverbrowneprima** [comment]
> You are absolutely right. Just did some more tests and we can simplify all of this!

Wooo! :partying_face:
